# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-19 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonrequestparam',
            name='api_info',
        ),
        migrations.RemoveField(
            model_name='response',
            name='api_info',
        ),
        migrations.DeleteModel(
            name='ApiInfo',
        ),
        migrations.DeleteModel(
            name='CommonRequestParam',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
