# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-20 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_responseheader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseheader',
            name='api_info',
        ),
        migrations.RemoveField(
            model_name='response',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='response',
            name='headers',
        ),
        migrations.DeleteModel(
            name='ResponseHeader',
        ),
    ]
