# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-20 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170420_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.CharField(max_length=128)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Response')),
            ],
        ),
    ]
