# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-23 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_apitestmethod_apitesttasktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitestmethod',
            name='api_test',
        ),
        migrations.RemoveField(
            model_name='apitesttasktype',
            name='api_test',
        ),
        migrations.DeleteModel(
            name='ApiTestMethod',
        ),
        migrations.DeleteModel(
            name='ApiTestTaskType',
        ),
    ]
