# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-23 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170423_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTestMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('param', models.CharField(max_length=256)),
                ('return_value', models.CharField(max_length=128)),
                ('api_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ApiInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ApiTestTaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('param', models.CharField(max_length=128)),
                ('api_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ApiInfo')),
            ],
        ),
    ]
