# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_apitestmethod_apitesttasktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitestmethod',
            name='param',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='apitestmethod',
            name='return_value',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='apitesttasktype',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='apitesttasktype',
            name='param',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
