# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170423_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitest',
            name='test_method',
            field=models.CharField(max_length=128),
        ),
    ]
