# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170425_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitest',
            name='api_info',
        ),
        migrations.DeleteModel(
            name='ApiTest',
        ),
    ]
