# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170425_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=128)),
                ('test_method', models.CharField(max_length=128)),
                ('param', models.CharField(max_length=128)),
                ('post_data', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=128)),
                ('task_type', models.CharField(max_length=128)),
                ('total_run', models.IntegerField(default=0)),
                ('success_run', models.IntegerField(default=0)),
                ('fail_run', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=128)),
                ('api_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ApiInfo')),
            ],
        ),
    ]
