# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-02 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_apitest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonrequestparam',
            name='value',
            field=models.CharField(max_length=1024),
        ),
    ]
