# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-03 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20170502_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitest',
            name='param',
            field=models.CharField(max_length=1024),
        ),
    ]
