# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-05 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20170505_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsebody',
            name='path',
            field=models.CharField(max_length=128),
        ),
    ]
