# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-07 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20170505_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='url_path',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
