# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_delete_apitestexecutelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTestExecuteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_time', models.CharField(max_length=128)),
                ('scheduled', models.BooleanField(default=False)),
                ('execute_result', models.BooleanField(default=False)),
                ('error_msg', models.CharField(max_length=256)),
            ],
        ),
    ]
