# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-02 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_apitestexecutelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitestexecutelog',
            name='error_msg',
            field=models.TextField(),
        ),
    ]
