# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-02 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170502_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestexecutelog',
            name='test_id',
            field=models.IntegerField(default=0),
        ),
    ]
