# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-09 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_apitestexecutelog_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestexecutelog',
            name='url',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
