# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timingtask',
            name='api_test_list',
            field=models.TextField(default=''),
        ),
    ]
