# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_timingtask_api_test_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtask',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timingtask',
            name='start_time',
            field=models.IntegerField(),
        ),
    ]
