# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-27 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20170426_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='timingtask',
            name='day_of_month',
            field=models.CharField(default='*', max_length=64),
        ),
        migrations.AddField(
            model_name='timingtask',
            name='day_of_week',
            field=models.CharField(default='*', max_length=64),
        ),
        migrations.AddField(
            model_name='timingtask',
            name='hour',
            field=models.CharField(default='*', max_length=64),
        ),
        migrations.AddField(
            model_name='timingtask',
            name='minute',
            field=models.CharField(default='*', max_length=64),
        ),
        migrations.AddField(
            model_name='timingtask',
            name='month_of_year',
            field=models.CharField(default='*', max_length=64),
        ),
        migrations.AddField(
            model_name='timingtask',
            name='run_time',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
