# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-28 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20170427_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtask',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
