# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-04 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_timingtask_run_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timingtask',
            name='run_time',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
