# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_delete_timingtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.IntegerField(),
        ),
    ]
