# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-28 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_customvalidaterule_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customvalidaterule',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
